# Generated by Django 4.1.1 on 2022-10-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="author_pseudonym",
            field=models.CharField(
                db_index=True,
                max_length=256,
                unique=True,
                verbose_name="author_pseudonym",
            ),
        ),
    ]
