name: Wookie Bookie CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [staging, "dev"]
  workflow_dispatch:

jobs:
  backend-build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}


      - name: Delete containers
        run: 		docker compose -f local.yml down

      - name: Delete db container
        run: 		docker rm -f wookie-bookie-db-1

      - name: Start containers
        run: 	docker compose -f local.yml up --build -d --remove-orphans

      - name: Run tests
        run: docker compose -f local.yml run --rm api python3 manage.py test apps/

      - name: Stop containers
        if: always()
        run: docker compose -f local.yml down

